name: CI

on: [push, pull_request]

env:
  IMAGE_NAME: heissenberg/covid-app
  IMAGE_TAG: golang-app-1.0
  SECURE_LOG_LEVEL: 'debug'
  USERNAME: ${{ secrets.REGISTRY_USER }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create annotation for build error
      run: echo "username is $USERNAME"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        sudo apt-get update
        sudo apt-get install -y make
        make test
